### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by TheSkripterDK** [thepn/ReplayAPI#2]
[ERROR] /C:/Users/danie/IdeaProjects/mavenaquask/src/main/java/de/sebpas/replay/recorder/listener/InteractListener.java:[1,24] class, interface, or enum expected
[ERROR] /C:/Users/danie/IdeaProjects/mavenaquask/src/main/java/de/sebpas/replay/recorder/listener/InteractListener.java:[1,25] illegal character: '\u0000'
[ERROR] /C:/Users/danie/IdeaProjects/mavenaquask/src/main/java/de/sebpas/replay/recorder/listener/InteractListener.java:[1,39] illegal character: '\u0000'
[ERROR] /C:/Users/danie/IdeaProjects/mavenaquask/src/main/java/de/sebpas/replay/recorder/listener/InteractListener.java:[1,53] illegal character: '\u0000'
[ERROR] /C:/Users/danie/IdeaProjects/mavenaquask/src/main/java/de/sebpas/replay/recorder/listener/InteractListener.java:[1,71] illegal character: '\u0000'
[ERROR] /C:/Users/danie/IdeaProjects/mavenaquask/src/main/java/de/sebpas/replay/recorder/listener/InteractListener.java:[1,89] illegal character: '\u0000'
[ERROR] /C:/Users/danie/IdeaProjects/mavenaquask/src/main/java/de/sebpas/replay/recorder/listener/InteractListener.java:[2,1] illegal character: '\u0000'
[ERROR] /C:/Users/danie/IdeaProjects/mavenaquask/src/main/java/de/sebpas/replay/recorder/listener/InteractListener.java:[3,1] illegal character: '\u0000'
[ERROR] /C:/Users/danie/IdeaProjects/mavenaquask/src/main/java/de/sebpas/replay/recorder/listener/InteractListener.java:[3,15] illegal character: '\u0000'
[ERROR] /C:/Users/danie/IdeaProjects/mavenaquask/src/main/java/de/sebpas/replay/recorder/listener/InteractListener.java:[3,22] class, interface, or enum expected
[ERROR] /C:/Users/danie/IdeaProjects/mavenaquask/src/main/java/de/sebpas/replay/recorder/listener/InteractListener.java:[3,23] illegal character: '\u0000'
[ERROR] /C:/Users/danie/IdeaProjects/mavenaquask/src/main/java/de/sebpas/replay/recorder/listener/InteractListener.java:[3,43] illegal character: '\u0000'
[ERROR] /C:/Users/danie/IdeaProjects/mavenaquask/src/main/java/de/sebpas/replay/recorder/listener/InteractListener.java:[3,57] illegal character: '\u0000'
[ERROR] /C:/Users/danie/IdeaProjects/mavenaquask/src/main/java/de/sebpas/replay/recorder/listener/InteractListener.java:[3,73] illegal character: '\u0000'
[ERROR] /C:/Users/danie/IdeaProjects/mavenaquask/src/main/java/de/sebpas/replay/recorder/listener/InteractListener.java:[3,93] illegal character: '\u0000'
[ERROR] /C:/Users/danie/IdeaProjects/mavenaquask/src/main/java/de/sebpas/replay/recorder/listener/InteractListener.java:[4,1] illegal character: '\u0000'
[ERROR] /C:/Users/danie/IdeaProjects/mavenaquask/src/main/java/de/sebpas/replay/recorder/listener/InteractListener.java:[5,1] illegal character: '\u0000'
[ERROR] /C:/Users/danie/IdeaProjects/mavenaquask/src/main/java/de/sebpas/replay/recorder/listener/InteractListener.java:[5,15] illegal character: '\u0000'
[ERROR] /C:/Users/danie/IdeaProjects/mavenaquask/src/main/java/de/sebpas/replay/recorder/listener/InteractListener.java:[5,22] class, interface, or enum expected
[ERROR] /C:/Users/danie/IdeaProjects/mavenaquask/src/main/java/de/sebpas/replay/recorder/listener/InteractListener.java:[5,23] illegal character: '\u0000'
[ERROR] /C:/Users/danie/IdeaProjects/mavenaquask/src/main/java/de/sebpas/replay/recorder/listener/InteractListener.java:[5,37] illegal character: '\u0000'
[ERROR] /C:/Users/danie/IdeaProjects/mavenaquask/src/main/java/de/sebpas/replay/recorder/listener/InteractListener.java:[5,61] illegal character: '\u0000'
[ERROR] /C:/Users/danie/IdeaProjects/mavenaquask/src/main/java/de/sebpas/replay/recorder/listener/InteractListener.java:[5,77] illegal character: '\u0000'
[ERROR] /C:/Users/danie/IdeaProjects/mavenaquask/src/main/java/de/sebpas/replay/recorder/listener/InteractListener.java:[5,97] illegal character: '\u0000'
[ERROR] /C:/Users/danie/IdeaProjects/mavenaquask/src/main/java/de/sebpas/replay/recorder/listener/InteractListener.java:[5,127] illegal character: '\u0000'
[ERROR] /C:/Users/danie/IdeaProjects/mavenaquask/src/main/java/de/sebpas/replay/recorder/listener/InteractListener.java:[6,1] illegal character: '\u0000'
[ERROR] /C:/Users/danie/IdeaProjects/mavenaquask/src/main/java/de/sebpas/replay/recorder/listener/InteractListener.java:[6,2] class, interface, or enum expected
[ERROR] /C:/Users/danie/IdeaProjects/mavenaquask/src/main/java/de/sebpas/replay/recorder/listener/InteractListener.java:[6,15] illegal character: '\u0000'

**Comment by pscln** [comment]
Try to use this one https://bitbucket.org/thepn/replayapi/
