### ISSUE TITLE
Still in development?

### ISSUE THREAD

**Issue by noX1609** [thepn/ReplayAPI#3]
Hi,

is this still in development?

Because creating a minecraft Network atm. and searching such a replay system for the network to catch hackers.

Does it always run or does it have a function so if a staff member gets a reporr about a cheating user he can teleport to the running game and start the recording? 
Both version would be ok but i would need it on version 1.12 / 1.12.1 because all servers are running on 1.12 or 1.12.1

Thanks in advice for an answer :)

**Comment by thepn** [comment]
this project is currently paused. Im sorry :c
